### ISSUE TITLE
Error removing in/out scope

### ISSUE THREAD

**Issue by pdelteil** [honoki/bbrf-client#100]
Hello there @honoki,

While removing the in/outscope of a program I got this error:

`[ERROR] object of type 'filter' has no len()`

But the data was removed as expected. 

Commands: 

`bbrf scope in -p PROGRAM| bbrf inscope remove -  `
`bbrf scope out -p PROGRAM| bbrf outscope remove -  `

**Comment by honoki** [comment]
Hi @pdelteil - looking at your commands I would guess you need to specify the program again:

`bbrf scope in -p PROGRAM | bbrf inscope remove - -p PROGRAM`

Otherwise you will try to remove the inscope of `PROGRAM` from whatever your currently active program is.

Please let me know if the problem persists, and feel free to reopen this issue. In that case, please can you include your inscope/outscope and the commands used?
