### ISSUE TITLE
How to remove a certain domain from resolved domains list ?

### ISSUE THREAD

**Issue by jakre1234** [honoki/bbrf-client#108]
Hey Devs,
I have been trying to remove a resolved domain from the ```bbrf domains resolved``` list but I can't see any example to delete a record from resolved list.

The only option is to do ```bbrf domain remove xxx.target.com``` but this basically removes the domain from domains list as well :(

**Comment by honoki** [comment]
Hi - the `--resolved` flag applies a filter to all domains and only returns the domains that have an IP address attached. In other words, you cannot remove a domain from the "resolved" list without removing the domain, because it is the same entry from the database that is being returned.

One way to achieve your desired result is to remove the domain and then add it again without resolutions:

```bash
bbrf domain remove xxx.target.com && bbrf domain add xxx.target.com
```

Another option is to directly update the JSON document in your database via the CouchDB API with `curl`:

```bash
curl -X PUT $(jq -r '.couchdb' ~/.bbrf/config.json)/xxx.target.com?rev=$(bbrf show xxx.target.com | jq -r '._rev') -u bbrf:$(jq -r .password ~/.bbrf/config.json) -d '{"ips":[]}'
```
