### ISSUE TITLE
[Question] How do I delete a program? 

### ISSUE THREAD

**Issue by pdelteil** [honoki/bbrf-client#17]
I don't see the option on the bbrf client.

**Comment by honoki** [comment]
Hi - deleting a program is not currently possible using the client interface because the way the database is structured it would require deleting all corresponding domains/ips/urls separately to avoid having orphaned documents in the db. It's now on the list to implement this. :)

You can disable a program with `bbrf disable program <program>` or manually remove it via the CouchDB Fauxton UI on `http://127.0.0.1:5984/_utils/#database/bbrf/<program>`

**Comment by pdelteil** [comment]
I understand.  

Thanks for your answer.

**Comment by pdelteil** [comment]
So, a way to do this is deleting all data from a program:

```
bbrf domains | bbrf domain remove - 
bbrf urls | bbrf url remove -
bbrf ips | bbrf ip remove -
```

I only need a way to remove a program (let's say it will only work is the program is empty), it could be something like this:

``bbrf program remove <program> ``
