### ISSUE TITLE
add_domains does't show any error message

### ISSUE THREAD

**Issue by thejeshgn** [honoki/bbrf-client#21]
- Try adding any out of scope domain
- No error message is thown and nothing gets added as well

**Comment by honoki** [comment]
Hi @thejeshgn - what would be the expected behaviour in this scenario?

I've intentionally designed bbrf not to be verbose when processing malformed input, so you can dump a whole lot of garbage into it, and it will only process what is relevant.

**Comment by thejeshgn** [comment]
I was thinking more like prints a table with domains that got added and domains that didnt

|domain |added|
|-------|-----|
|xx.com | 1   |
|abc.com| 0   |

**Comment by honoki** [comment]
Have a look at the `--show-new` flag, which partially covers what you describe:

```
  --show-new    Print new unique values that were added to the database, and didn't already exist
```

Anything not listed as a "new" when using this flag either doesn't match the inscope or otherwise already existed in the database. I'll think about the need for a flag to display omitted input, but I don't see any immediate use for it.
