### ISSUE TITLE
[Question] Latest server update, need to rebuild documents manually?

### ISSUE THREAD

**Issue by pdelteil** [honoki/bbrf-client#71]
I noticed this after the server update:

```
> bbrf show http://zz.wordpress.org

{"_id":"http://zz.wordpress.org","_rev":"1-74e81b687943d0bd2ad994d99382b784","program":"Wordpress",
"type":"url","hostname":"zz.wordpress.org","port":80,"query":[],"source":"httprobe"} 
```

Then I tried to add it again 
 ```
> echo "http://zz.wordpress.org"| bbrf url add - -p@INFER --show-new 
[UPDATED] http://zz.wordpress.org
```
It says 'updated' now if I recheck the URL: 

```
> bbrf show http://zz.wordpress.org
{"_id":"http://zz.wordpress.org","_rev":"2-cf0725a8e1f13c45a9a32fd2148c0454","hostname":"zz.wordpress.org",
"port":80,"query":[],"scheme":"http","path":"","source":"httprobe","program":"Wordpress","type":"url"}
```

Does this mean that I will need to manually update all URLs ? 
Something failed on my end?

**Comment by honoki** [comment]
Hi - this is expected behaviour. BBRF v1.1.11 makes some minor changes to the way URLs are stored, but an upgrade does not attempt to retroactively update all documents in the database. If you want all your documents to align with the new structure, you should be able to just run `bbrf urls -A | bbrf url update -`

**Comment by pdelteil** [comment]
Hi,

Yes, I noticed the changes (very useful by the way)
