### ISSUE TITLE
Support for advanced query operators in `where` statements

### ISSUE THREAD

**Issue by Regala** [honoki/bbrf-client#84]
The tag feature is immensely helpful. However there are sometimes where you'd want to query multiple tags at the same time, e.g.:

`bbrf urls where source is subfinder and cve is cve-2021-1337` 

By chaining those tags we could do very fine grained searches on the documents (maybe this is already possible somehow and I just don't know how). 

Personally I think the `and` would be more than enough but having an `or` would make it even better.

**Comment by 0xblackbird** [comment]
I'm also experiencing the same thing, I really need the 'and' operator to query for multiple tags. I thought that it'd be easy to implement this but it turns out that that couchdb doesn't really support this, I might 've overlooked this but as far as I know, couchdb can't do this (yet). But we can use a little workaround this of course. I'm currently working on it, I will try to create a pull request in the coming days

**Comment by 0xblackbird** [comment]
I got it to work by using startkey and endkey in couchdb which then looked at the documents where both of the keys and values were seen and it returns you the id of the document (in this case domain name). I'm unsure if this is the best way to do it, I guess it even can be done with couchdb but I'm fairly new to that so I haven't had the time to try that out. 
(The OR operator can be implemented via a view on couchdb)

**Comment by Regala** [comment]
Great job @0xblackbird, this is awesome!

**Comment by honoki** [comment]
This has been implemented!
